[news]
title = "씨네21 모바일 ─ 뉴스"
url = "http://m.cine21.com/news/lists/?s=0"
entrySelector = "ul.lst_top2 li"
titleSelector = "div.tit"
linkSelector = "a"
contentSelector = "div.category"
imageSelector = "div.thub img"
waitUntil = "networkidle"

[news_special]
title = "씨네21 모바일 ─ 스페셜"
url = "http://m.cine21.com/news/lists/?s=2"
entrySelector = "ul.lst_bigimg li"
titleSelector = "div.tit"
linkSelector = "a"
contentSelector = "div.cont"
imageSelector = "div.thub img"
waitUntil = "networkidle"

[news_critic]
title = "씨네21 모바일 ─ 평론"
url = "http://m.cine21.com/news/lists/?s=5"
entrySelector = "ul.lst_bigimg li"
titleSelector = "div.tit"
linkSelector = "a"
contentSelector = "div.cont"
imageSelector = "div.thub img"
waitUntil = "networkidle"

[news_column]
title = "씨네21 모바일 ─ 칼럼"
url = "http://m.cine21.com/news/lists/?s=1"
entrySelector = "ul.lst_bigimg li"
titleSelector = "div.tit"
linkSelector = "a"
contentSelector = "div.cont"
imageSelector = "div.thub img"
waitUntil = "networkidle"

[news_review]
title = "씨네21 모바일 ─ 리뷰"
url = "http://m.cine21.com/news/lists/?s=3"
entrySelector = "ul.lst_bigimg li"
titleSelector = "div.tit"
linkSelector = "a"
contentSelector = "div.cont"
imageSelector = "div.thub img"
waitUntil = "networkidle"

[news_culture]
title = "씨네21 모바일 ─ 컬쳐"
url = "http://m.cine21.com/news/lists/?s=7"
entrySelector = "ul.lst_bigimg li"
titleSelector = "div.tit"
linkSelector = "a"
contentSelector = "div.cont"
imageSelector = "div.thub img"
waitUntil = "networkidle"

[news_interview]
title = "씨네21 모바일 ─ 인터뷰"
url = "http://m.cine21.com/news/lists/?s=4"
entrySelector = "ul.lst_bigimg li"
titleSelector = "div.tit"
linkSelector = "a"
contentSelector = "div.cont"
imageSelector = "div.thub img"
waitUntil = "networkidle"

[news_filmfest]
title = "씨네21 모바일 ─ 영화제"
url = "http://m.cine21.com/news/lists/?s=8"
entrySelector = "ul.lst_bigimg li"
titleSelector = "div.tit"
linkSelector = "a"
contentSelector = "div.cont"
imageSelector = "div.thub img"
waitUntil = "networkidle"

[news_dailynews_top]
title = "씨네21 모바일 ─ 데일리뉴스 하이라이트"
url = "http://m.cine21.com/news/issue"
entrySelector = "div.topnews"
titleSelector = "div.topnews_tit span"
linkSelector = "a"
contentSelector = "div.topnews_tit"
imageSelector = "a img"
waitUntil = "networkidle"

[news_dailynews]
title = "씨네21 모바일 ─ 데일리뉴스"
url = "http://m.cine21.com/news/issue"
entrySelector = "ul.lst_card li"
titleSelector = "div.tit p"
linkSelector = "a"
contentSelector = "div.tit"
imageSelector = "div.thub img"
waitUntil = "networkidle"

[review_starrating]
title = "씨네21 모바일 ─ 별점"
url = "http://m.cine21.com/movie/review/recent"
entrySelector = "ul.lst_card li"
titleSelector = "div.tit p"
linkSelector = "div.card_wrap a"
contentSelector = "div.ico_star p"
imageSelector = "div.thub img"
waitUntil = "networkidle"

[photo_cover]
title = "씨네21 모바일 ─ 사진 ─ 커버"
url = "http://m.cine21.com/photo/cover"
entrySelector = "ul.lst_card li"
titleSelector = "div.cover_num"
linkSelector = "div.thub img"
contentSelector = "div.cover_num"
imageSelector = "div.thub img"
waitUntil = "networkidle"

[photo_person]
title = "씨네21 모바일 ─ 사진 ─ 인물"
url = "http://m.cine21.com/photo/person"
entrySelector = "ul.lst_card li"
titleSelector = "div.name"
linkSelector = "a"
contentSelector = "div.role"
imageSelector = "div.thub img"
waitUntil = "networkidle"