[contents]
title = "씨네21 모바일"
url = "http://m.cine21.com/news/contents/"
entrySelector = "li.nml"
titleSelector = "div.tit"
linkSelector = "a"
contentSelector = "div.category"
imageSelector = "div.thub img"
waitUntil = "networkidle"
